GET http://localhost:4004/odata/v4/polaris/TIMESHEET_SRV/Timedetails

######
GET http://localhost:4004/odata/v4/polaris/TIMESHEET_SRV/Attachments


####
POST http://localhost:4004/odata/v4/polaris/TIMESHEET_SRV/Timedetails
Content-Type: application/json

{
      "PERNR": 17,
      "PAYROLL_AREA": "AB",
      "DATE": "2020-12-20",
      "SEQ_NUM": 1,
      "TIMEIN": "09:00:00",
      "TIMEOUT": "17:00:00",
      "ATT_ABS_CODE": "02",
      "attachmentitems": [{
          "DocType" : "PDF"
      }]

} 

####

POST http://localhost:4004/odata/v4/polaris/TIMESHEET_SRV/Attachments
Content-Type: application/json

####
